export default {
  data: {
    page_type: 'offer',
    name: 'Matts Products',
    description: '',
    slug: 'index.html',
    checkout_url: '',
    prod_name: 'S3 Video Offers',
    theme: { color: '#e91e63', dark: false, spaceY: 3 },
    meta: {},
    header_code: '',
    footer_code: '',
    bg: {
      src: 'https://images.unsplash.com/photo-1605102275264-56c12df905fa?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218MHwzMzYyOTkzfHx8fHx8fDE2NjE4NTAyODc&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1600',
      mobiSrc:
        'https://images.unsplash.com/photo-1605102275264-56c12df905fa?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=890&ixid=MnwxfDB8MXxyYW5kb218MHwzMzYyOTkzfHx8fHx8fDE2NjE4NTAyODc&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=400',
      filter: 'blur(0px) grayscale(0%) brightness(100%)',
    },
    seo: {
      title: '',
      image: '',
      description: '',
      keywords: '',
      sponsored: false,
      nofollow: false,
      noindex: false,
    },
    body: {
      type: 'body',
      props: {},
      opts: {},
      children: [
        {
          type: 'main',
          name: null,
          children: [
            {
              type: 'section',
              name: null,
              children: [
                {
                  type: 'block',
                  name: 'Buy Button',
                  children: [
                    {
                      type: 'box',
                      name: null,
                      children: [
                        {
                          type: 'text',
                          name: 'Text',
                          children: null,
                          timed: null,
                          id: 'TtxTetyvzDaivO__qsXdY',
                          props: {
                            highlight: false,
                            bold: false,
                            italic: false,
                            underline: false,
                            textSize: 'h5',
                            textAlign: 'center',
                            textColor: '',
                          },
                          opts: {},
                          textContent: 'Claim Your Access Now!',
                          disabled: false,
                        },
                      ],
                      timed: null,
                      props: {
                        pl: null,
                        pr: null,
                        pt: null,
                        pb: null,
                        ml: null,
                        mr: null,
                        mt: null,
                        mb: null,
                      },
                      opts: {},
                      id: 'J8hRVLYbCZmquF5aXCdsM',
                      childProps: {},
                      disabled: false,
                    },
                    {
                      type: 'box',
                      name: 'Buy Button',
                      children: [
                        {
                          type: 'buy-btn',
                          name: 'Buy Button',
                          children: null,
                          timed: null,
                          props: {
                            checkout: true,
                            cart: true,
                            cards: true,
                            paypal: true,
                            size: 'x-large',
                          },
                          opts: { checkout: true, src: false },
                          textContent: 'Buy Now!',
                          id: 'QxIduhCo-4poH8x7pkprY',
                          disabled: false,
                        },
                      ],
                      timed: null,
                      props: {
                        pl: null,
                        pr: null,
                        pt: null,
                        pb: null,
                        ml: null,
                        mr: null,
                        mt: null,
                        mb: null,
                      },
                      opts: {},
                      id: 'zAAya_X-q0L1mNDCjmlK6',
                      childProps: {},
                      disabled: false,
                    },
                  ],
                  timed: null,
                  props: {
                    pl: null,
                    pr: null,
                    pt: null,
                    pb: null,
                    ml: null,
                    mr: null,
                    mt: null,
                    mb: null,
                  },
                  opts: {},
                  id: '65jGMFw-Cr5u2KxCvDNMD',
                  childProps: { cols: 12 },
                  disabled: false,
                },
                {
                  type: 'block',
                  name: 'Video',
                  children: [
                    {
                      type: 'box',
                      name: 'Video',
                      children: [
                        {
                          type: 'video',
                          name: 'Video',
                          children: null,
                          timed: null,
                          props: {
                            src: 'https://player.vimeo.com/progressive_redirect/playback/744156345/rendition/720p/file.mp4?loc=external&signature=8a4be4bc5db7d6158a4c8077f87f0c58392dfb0d5c9f6595118e36f6dff88904',
                            poster:
                              'https://i.vimeocdn.com/video/1497111507-4153ca85d315a290e1c60f9d3b133c7f049e91214554e8f5e248ec54bb2e2c21-d_640',
                            service: 'video',
                            color: '',
                            preview: false,
                            noControls: false,
                            noPause: false,
                            elevation: 0,
                            edged: false,
                          },
                          opts: {},
                          service: 'video',
                          duration: 11.605,
                          id: 'ISTHGLa6mOBrvnZzZYrmh',
                          disabled: false,
                        },
                      ],
                      timed: null,
                      props: {
                        pl: null,
                        pr: null,
                        pt: null,
                        pb: null,
                        ml: null,
                        mr: null,
                        mt: null,
                        mb: null,
                      },
                      opts: {},
                      id: 'nS09yiixehTMCbi3wK6JH',
                      childProps: {},
                      disabled: false,
                    },
                  ],
                  timed: null,
                  props: {
                    pl: null,
                    pr: null,
                    pt: null,
                    pb: null,
                    ml: null,
                    mr: null,
                    mt: null,
                    mb: null,
                  },
                  opts: {},
                  id: '1KFaMRyIJjzOJ__mnXHmK',
                  childProps: { cols: 12 },
                  disabled: false,
                },
              ],
              timed: null,
              props: {
                pl: null,
                pr: null,
                pt: null,
                pb: null,
                ml: null,
                mr: null,
                mt: null,
                mb: null,
              },
              opts: {},
              id: 'JwXMDgOsaLWg2wr5Xix9C',
              childProps: { mb: 0 },
              disabled: false,
            },
          ],
          timed: null,
          props: {
            pl: null,
            pr: null,
            pt: null,
            pb: null,
            ml: null,
            mr: null,
            mt: null,
            mb: null,
            pa: 3,
            my: 3,
            elevation: 3,
            color: '',
            rounded: 'lg',
          },
          opts: {},
          id: 'RbxNYj9sRMLhYXnC5Q1Yr',
          disabled: false,
        },
        {
          type: 'footer',
          name: null,
          children: [
            {
              type: 'box',
              name: null,
              children: [
                {
                  type: 'links',
                  name: null,
                  children: [
                    {
                      type: 'btn',
                      name: 'Button',
                      children: null,
                      timed: null,
                      props: {
                        color: '',
                        checkout: false,
                        openNew: true,
                      },
                      opts: {},
                      textContent: 'Terms',
                      id: 'GyZWD9ITTtiyR5---DaO2',
                      disabled: false,
                    },
                    {
                      type: 'btn',
                      name: 'Button',
                      children: null,
                      timed: null,
                      props: {
                        color: '',
                        checkout: false,
                        openNew: true,
                      },
                      opts: {},
                      textContent: 'Privacy',
                      id: 'mlfQlmXYiHtSdNZ3yjvMU',
                      disabled: false,
                    },
                    {
                      type: 'btn',
                      name: 'Button',
                      children: null,
                      timed: null,
                      props: {
                        color: '',
                        checkout: false,
                        openNew: true,
                      },
                      opts: {},
                      textContent: 'Disclaimer',
                      id: 'P9hh8gctzrgAA_vFdgA4v',
                      disabled: false,
                    },
                  ],
                  timed: null,
                  props: { justify: 'center', align: 'center' },
                  opts: {},
                  childProps: {
                    color: '#9e9e9e',
                    variant: 'text',
                    mx: 0,
                    my: 0,
                  },
                  id: 'dOWEQbq6BX2PV3UGgqLgr',
                  disabled: false,
                },
              ],
              timed: null,
              props: {
                pl: null,
                pr: null,
                pt: null,
                pb: null,
                ml: null,
                mr: null,
                mt: null,
                mb: null,
              },
              opts: {},
              id: 'Ds0BGFtrCmdJCmnwZsJXw',
              childProps: {},
              disabled: false,
            },
            {
              type: 'box',
              name: null,
              children: [
                {
                  type: 'text',
                  name: 'Text',
                  children: null,
                  timed: null,
                  id: '3bzSFamt-qG04h8Ijz1Iz',
                  props: { textSize: 'caption', textAlign: 'center' },
                  opts: {},
                  textContent: 'Copyright \u00a9',
                  disabled: false,
                },
              ],
              timed: null,
              props: {
                pl: 0,
                pr: 0,
                pt: 0,
                pb: 0,
                ml: null,
                mr: null,
                mt: null,
                mb: null,
                elevation: 0,
              },
              opts: {},
              id: 'qAn9m-agkRhpb0Tvem4nN',
              childProps: {},
              disabled: false,
            },
          ],
          timed: null,
          id: '5FS6ntFMl3KnKgqS5htbH',
          opts: {},
          props: { pl: 0, pr: 0, pt: 0, pb: 0, elevation: 0, dark: true },
          childProps: { cols: 12 },
          disabled: false,
        },
      ],
    },
    opts: {},
  },
}
