export default {
  type: 'body',
  props: {},
  opts: {},
  children: [
    {
      type: 'main',
      name: null,
      children: [
        {
          type: 'section',
          name: null,
          children: [
            {
              type: 'block',
              name: 'Image',
              children: [
                {
                  type: 'box',
                  name: null,
                  children: [
                    {
                      type: 'image',
                      name: 'Image',
                      children: [],
                      timed: null,
                      id: 'eC7BzaLZOlN30C2Lv0iSt',
                      props: {
                        pl: null,
                        pr: null,
                        pt: null,
                        pb: null,
                        ml: null,
                        mr: null,
                        mt: null,
                        mb: null,
                        checkout: false,
                        openNew: false,
                        src: 'https://wp-buckets-images.s3.amazonaws.com/Screenshot%202022-07-30%20at%2023.38.05.png',
                      },
                      opts: {},
                      disabled: false,
                    },
                  ],
                  timed: null,
                  props: {
                    pl: null,
                    pr: null,
                    pt: null,
                    pb: null,
                    ml: null,
                    mr: null,
                    mt: null,
                    mb: null,
                  },
                  opts: {},
                  id: 'Rmg8vaq3Tqdejp2fES6z_',
                  childProps: {},
                  disabled: false,
                },
              ],
              timed: null,
              props: {
                pl: null,
                pr: null,
                pt: null,
                pb: null,
                ml: null,
                mr: null,
                mt: null,
                mb: null,
              },
              opts: {},
              id: 'rkMSbmrYL1JubxdDkYzKm',
              childProps: { cols: 12 },
              disabled: false,
            },
          ],
          timed: null,
          props: {
            pl: null,
            pr: null,
            pt: null,
            pb: null,
            ml: null,
            mr: null,
            mt: null,
            mb: null,
          },
          opts: {},
          id: 'JwXMDgOsaLWg2wr5Xix9C',
          childProps: { mb: 16 },
          disabled: false,
        },
      ],
      timed: null,
      props: {
        pl: null,
        pr: null,
        pt: null,
        pb: null,
        ml: null,
        mr: null,
        mt: null,
        mb: null,
        pa: 0,
        my: 6,
        elevation: 8,
        rounded: 'lg',
        color: '',
        fillHeight: true,
        nudgeUp: false,
      },
      opts: {},
      id: 'RbxNYj9sRMLhYXnC5Q1Yr',
      disabled: false,
    },
    {
      type: 'footer',
      name: null,
      children: [
        {
          type: 'box',
          name: null,
          children: [
            {
              type: 'links',
              name: null,
              children: [
                {
                  type: 'btn',
                  name: 'Button',
                  children: null,
                  timed: null,
                  props: { color: '', checkout: false, openNew: true },
                  opts: {},
                  textContent: 'Terms',
                  id: 'GyZWD9ITTtiyR5---DaO2',
                  disabled: false,
                },
                {
                  type: 'btn',
                  name: 'Button',
                  children: null,
                  timed: null,
                  props: { color: '', checkout: false, openNew: true },
                  opts: {},
                  textContent: 'Privacy',
                  id: 'mlfQlmXYiHtSdNZ3yjvMU',
                  disabled: false,
                },
                {
                  type: 'btn',
                  name: 'Button',
                  children: null,
                  timed: null,
                  props: { color: '', checkout: false, openNew: true },
                  opts: {},
                  textContent: 'Disclaimer',
                  id: 'P9hh8gctzrgAA_vFdgA4v',
                  disabled: false,
                },
              ],
              timed: null,
              props: { justify: 'center', align: 'center' },
              opts: {},
              childProps: { color: '#9e9e9e', variant: 'text', mx: 0, my: 0 },
              id: 'dOWEQbq6BX2PV3UGgqLgr',
              disabled: false,
            },
          ],
          timed: null,
          props: {
            pl: null,
            pr: null,
            pt: null,
            pb: null,
            ml: null,
            mr: null,
            mt: null,
            mb: null,
          },
          opts: {},
          id: 'Ds0BGFtrCmdJCmnwZsJXw',
          childProps: {},
          disabled: false,
        },
        {
          type: 'box',
          name: null,
          children: [
            {
              type: 'text',
              name: 'Text',
              children: null,
              timed: null,
              id: '3bzSFamt-qG04h8Ijz1Iz',
              props: {
                textSize: 'caption',
                textAlign: 'center',
                textColor: 'rgba(117, 117, 117, 1)',
              },
              opts: {},
              textContent: 'Copyright ©',
              disabled: false,
            },
          ],
          timed: null,
          props: {
            pl: 0,
            pr: 0,
            pt: 0,
            pb: 0,
            ml: null,
            mr: null,
            mt: null,
            mb: null,
            elevation: 0,
          },
          opts: {},
          id: 'qAn9m-agkRhpb0Tvem4nN',
          childProps: {},
          disabled: false,
        },
      ],
      timed: null,
      id: '5FS6ntFMl3KnKgqS5htbH',
      opts: {},
      props: {
        pl: 0,
        pr: 0,
        pt: 0,
        pb: 0,
        elevation: 0,
        color: '',
        dark: true,
      },
      childProps: { cols: 12 },
      disabled: true,
    },
  ],
}
