export default [
  {
    name: 'N. Virginia',
    fullName: 'US East (N. Virginia)',
    value: 'us-east-1',
    public: true,
    zones: [
      'us-east-1a',
      'us-east-1b',
      'us-east-1c',
      'us-east-1d',
      'us-east-1e',
      'us-east-1f',
    ],
  },
  {
    name: 'Ohio',
    fullName: 'US East (Ohio)',
    value: 'us-east-2',
    public: true,
    zones: ['us-east-2a', 'us-east-2b', 'us-east-2c'],
  },
  {
    name: 'N. California',
    fullName: 'US West (N. California)',
    value: 'us-west-1',
    public: true,
    zone_limit: 2,
    zones: ['us-west-1a', 'us-west-1b', 'us-west-1c'],
  },
  {
    name: 'Oregon',
    fullName: 'US West (Oregon)',
    value: 'us-west-2',
    public: true,
    zones: ['us-west-2a', 'us-west-2b', 'us-west-2c', 'us-west-2d'],
  },
  {
    name: 'GovCloud West',
    fullName: 'AWS GovCloud (US)',
    value: 'us-gov-west-1',
    public: false,
    zones: ['us-gov-west-1a', 'us-gov-west-1b', 'us-gov-west-1c'],
  },
  {
    name: 'GovCloud East',
    fullName: 'AWS GovCloud (US-East)',
    value: 'us-gov-east-1',
    public: false,
    zones: ['us-gov-east-1a', 'us-gov-east-1b', 'us-gov-east-1c'],
  },
  {
    name: 'Canada',
    fullName: 'Canada (Central)',
    value: 'ca-central-1',
    public: true,
    zones: ['ca-central-1a', 'ca-central-1b', 'ca-central-1c', 'ca-central-1d'],
  },
  {
    name: 'Stockholm',
    fullName: 'EU (Stockholm)',
    value: 'eu-north-1',
    public: true,
    zones: ['eu-north-1a', 'eu-north-1b', 'eu-north-1c'],
  },
  {
    name: 'Ireland',
    fullName: 'EU (Ireland)',
    value: 'eu-west-1',
    public: true,
    zones: ['eu-west-1a', 'eu-west-1b', 'eu-west-1c'],
  },
  {
    name: 'London',
    fullName: 'EU (London)',
    value: 'eu-west-2',
    public: true,
    zones: ['eu-west-2a', 'eu-west-2b', 'eu-west-2c'],
  },
  {
    name: 'Paris',
    fullName: 'EU (Paris)',
    value: 'eu-west-3',
    public: true,
    zones: ['eu-west-3a', 'eu-west-3b', 'eu-west-3c'],
  },
  {
    name: 'Frankfurt',
    fullName: 'EU (Frankfurt)',
    value: 'eu-central-1',
    public: true,
    zones: ['eu-central-1a', 'eu-central-1b', 'eu-central-1c'],
  },
  {
    name: 'Milan',
    fullName: 'EU (Milan)',
    value: 'eu-south-1',
    public: true,
    zones: ['eu-south-1a', 'eu-south-1b', 'eu-south-1c'],
  },
  {
    name: 'Cape Town',
    fullName: 'Africa (Cape Town)',
    value: 'af-south-1',
    public: true,
    zones: ['af-south-1a', 'af-south-1b', 'af-south-1c'],
  },
  {
    name: 'Tokyo',
    fullName: 'Asia Pacific (Tokyo)',
    value: 'ap-northeast-1',
    public: true,
    zone_limit: 3,
    zones: [
      'ap-northeast-1a',
      'ap-northeast-1b',
      'ap-northeast-1c',
      'ap-northeast-1d',
    ],
  },
  {
    name: 'Seoul',
    fullName: 'Asia Pacific (Seoul)',
    value: 'ap-northeast-2',
    public: true,
    zones: [
      'ap-northeast-2a',
      'ap-northeast-2b',
      'ap-northeast-2c',
      'ap-northeast-2d',
    ],
  },
  {
    name: 'Osaka',
    fullName: 'Asia Pacific (Osaka-Local)',
    value: 'ap-northeast-3',
    public: true,
    zones: ['ap-northeast-3a', 'ap-northeast-3b', 'ap-northeast-3c'],
  },
  {
    name: 'Singapore',
    fullName: 'Asia Pacific (Singapore)',
    value: 'ap-southeast-1',
    public: true,
    zones: ['ap-southeast-1a', 'ap-southeast-1b', 'ap-southeast-1c'],
  },
  {
    name: 'Sydney',
    fullName: 'Asia Pacific (Sydney)',
    value: 'ap-southeast-2',
    public: true,
    zones: ['ap-southeast-2a', 'ap-southeast-2b', 'ap-southeast-2c'],
  },
  {
    name: 'Jakarta',
    fullName: 'Asia Pacific (Jakarta)',
    value: 'ap-southeast-3',
    public: true,
    zones: ['ap-southeast-3a', 'ap-southeast-3b', 'ap-southeast-3c'],
  },
  {
    name: 'Hong Kong',
    fullName: 'Asia Pacific (Hong Kong)',
    value: 'ap-east-1',
    public: true,
    zones: ['ap-east-1a', 'ap-east-1b', 'ap-east-1c'],
  },
  {
    name: 'Mumbai',
    fullName: 'Asia Pacific (Mumbai)',
    value: 'ap-south-1',
    public: true,
    zones: ['ap-south-1a', 'ap-south-1b', 'ap-south-1c'],
  },
  {
    name: 'São Paulo',
    fullName: 'South America (São Paulo)',
    value: 'sa-east-1',
    public: true,
    zone_limit: 2,
    zones: ['sa-east-1a', 'sa-east-1b', 'sa-east-1c'],
  },
  {
    name: 'Bahrain',
    fullName: 'Middle East (Bahrain)',
    value: 'me-south-1',
    public: true,
    zones: ['me-south-1a', 'me-south-1b', 'me-south-1c'],
  },
  {
    name: 'Beijing',
    fullName: 'China (Beijing)',
    value: 'cn-north-1',
    public: false,
    zones: ['cn-north-1a', 'cn-north-1b', 'cn-north-1c'],
  },
  {
    name: 'Ningxia',
    fullName: 'China (Ningxia)',
    value: 'cn-northwest-1',
    public: false,
    zones: ['cn-northwest-1a', 'cn-northwest-1b', 'cn-northwest-1c'],
  },
]
